### PR TITLE
Implement Debug for VulkanAllocator. 

### PR DESCRIPTION
**Pull request by hrydgard**
An easy way to dump out the whole state in a panic.

### CODE REVIEW

**Comment by MarijnS95** [comment]
Would it make sense to use `finish_non_exhaustive` to indicate that not all fields are printed, despite them being "internal" or "irrelevant"? I wonder if `memory_heaps` could be interesting to see, even if only used for the visualizer.

**Comment by hrydgard** [comment]
memory_heaps only contains vk::MemoryHeap pointers, not too interesting on its own. Could of course query out information from them I guess, but seems out of scope for an initial take. And doing `#[cfg(feature = "visualizer")]` in the middle of a chain doesn't work (can of course rewrite it so it does work, but it better be worth it and doesn't seem to be).

Switching to finish_non_exhaustive though, didn't know about that one.

**Review by MarijnS95 — APPROVED** [review]

**Comment by MarijnS95** [comment]
FWIW `vk::MemoryHeap` aren't pointers but structs (at specific array indices) holding the size of a heap and its flags. It may be interesting in the future, but for now `finish_non_exhaustive` suffices. Thanks!

**Comment by hrydgard** [comment]
Oh, my bad then! Curious why it's only there when the visualizer is enabled?

**Comment by MarijnS95** [comment]
The heaps (or rather, the indices in `MemortyType::heap_index`) are interesting to see what `MemoryType` lives where (ie. if certain types share the same physical memory area) and how large that area of physical memory is, but are not relevant to the allocation algorithm, given that flags such as `DEVICE_LOCAL` and `HOST_VISIBLE` are fully covered in `MemoryType::property_flags`.

**Pull request merged**
