### PR TITLE
bump ash to 0.34, ash-window to 0.8

### PR DESCRIPTION
**Pull request by adrien-ben**
Tested the vulkan examples and they work fine.

### CODE REVIEW

**Review by Jasper-Bekkers — APPROVED** [review]

**Comment by adrien-ben** [comment]
I should have tested d3d12 examples as well.
I'm not sure why https://github.com/Traverse-Research/gpu-allocator/pull/86/files#diff-3f6a4bd27ac6c7b39899ceddf5853c5a29adeb30817221abea86029469c85013R215 fails.

```
error[E0277]: the trait bound `winit::window::Window: HasRawWindowHandle` is not satisfied
```

**Comment by Jasper-Bekkers** [comment]
@adrien-ben don't worry about it, @MarijnS95 seems to also have opened a PR to address this as #87

**Comment by adrien-ben** [comment]
winit 0.26 fixes it but then it breaks vulkan examples because of `imgui-winit-support` so I reverted `raw-window-handle` back to 0.3. 

I'll close this one since @MarijnS95's seem more complete with disabling `linked` feature from ash.

**Comment by MarijnS95** [comment]
Hi @adrien-ben, thanks for doing this, and right at the same time!

No worries, it's just unfortunate that I didn't submit this branch right after publishing the `ash` release (it was almost 3AM :grin:, and haven't been available all day) and made you go through all this trouble :sweat_smile: - sorry for that!

Feel free to pick up the `winit 0.26` upgrade once `imgui-winit-support` for it is available, that'd be appreciated!

**Comment by adrien-ben** [comment]
Hi @MarijnS95, no problem ! :) 

By the way thank you for all the work with ash and rust/vulkan related stuff. Helps me a lot ! 

Alright !

**Pull request closed without merging**
