### PR TITLE
cargo: Bump `windows` crate range to `0.53-0.57`

### PR DESCRIPTION
**Pull request by MarijnS95**
Allow `windows 0.53` all the way up to and including `0.57` to be used, and remove some unused features from the core crate.

### CODE REVIEW

**Comment by Systemcluster** [comment]
The `ComInterface` trait seems to be just `Interface` since `0.53`: https://github.com/microsoft/windows-rs/issues/2875#issuecomment-1962332067

I'm not sure why it's not mentioned in the release notes. `Interface` seems to work down to at least `0.51` though, so I think you can just replace it without bumping the lower version bound.

**Comment by cwfitzgerald** [comment]
This would be great to get in, I've started depending on it locally.

**Comment by MarijnS95** [comment]
Looks like `0.57` requires an MSRV bump to Rust 1.70.

**Review by tosti007 — APPROVED** [review]

**Comment by MarijnS95** [comment]
Ugh, the merge-commit title failed to update.

**Pull request merged**
